// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://qyicvjnhdkewvebpfzrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5aWN2am5oZGtld3ZlYnBmenJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4ODcyNzcsImV4cCI6MjA3NjQ2MzI3N30.o_7KUZu1mwulRdTm780Gudx2pry8b7pZy1OhAOaGEWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
